apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: basket
    spec:
      containers:
      - name: basket
        image: registry.zhaw.tk:4443/eshop/basket.api
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80/basket-api
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionString
          value: 127.0.0.1
        - name: EventBusConnection
          value: rabbitmq
        - name: IdentityUrl
          value: "http://identity"
        ports:
        - containerPort: 80
      - name: basket-data
        image: redis:3.2-alpine
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: catalog
    spec:
      containers:
      - name: catalog
        image: registry.zhaw.tk:4443/eshop/catalog.api
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80/catalog-api
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionString
          value: "Server=sql-data;Initial Catalog=Microsoft.eShopOnContainers.Services.CatalogDb;User Id=sa;Password=Pass@word"
        - name: EventBusConnection
          value: rabbitmq
        - name: ExternalCatalogBaseUrl
          value: "http://catalog"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: identity
    spec:
      containers:
      - name: identity
        image: registry.zhaw.tk:4443/eshop/identity.api
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80/identity
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionStrings__DefaultConnection
          value: "Server=sql-data;Initial Catalog=Microsoft.eShopOnContainers.Services.IdentityDb;User Id=sa;Password=Pass@word"
        - name: MvcClient
          value: "http://webmvc"
        - name: SpaClient
          value: "http://webspa"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ordering
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: ordering
    spec:
      containers:
      - name: ordering
        image: registry.zhaw.tk:4443/eshop/ordering.api
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80/ordering-api
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ConnectionString
          value: "Server=sql-data;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word;"
        - name: EventBusConnection
          value: rabbitmq
        - name: IdentityUrl
          value: "http://identity"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webmvc
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: webmvc
    spec:
      containers:
      - name: webmvc
        image: registry.zhaw.tk:4443/eshop/webmvc
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80/webmvc
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: BasketUrl
          value: "http://basket"
        - name: CallBackUrl
          value: "http://webmvc"
        - name: CatalogUrl
          value: "http://catalog"
        - name: IdentityUrl
          value: "http://identity"
        - name: OrderingUrl
          value: "http://ordering"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webspa
  namespace: shop
spec:
  template:
    metadata:
      labels:
        app: eshop
        component: webspa
    spec:
      containers:
      - name: webspa
        image: registry.zhaw.tk:4443/eshop/webspa
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://0.0.0.0:80
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: BasketUrl
          value: "http://basket"
        - name: CallBackUrl
          value: "http://webspa"
        - name: CatalogUrl
          value: "http://catalog"
        - name: IdentityUrl
          value: "http://identity"
        - name: OrderingUrl
          value: "http://ordering"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: registry-key
