kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: shop
  namespace: shop
  labels:
    # let kube-cert-manager generate an SSL certificate
    stable.k8s.psg.io/kcm.class: "default"
spec:
  tls:
  - hosts:
    - shop.zhaw.tk
    secretName: shop-tls-cert
  rules:
  - host: shop.zhaw.tk
    http:
      paths:
      - path: /basket-api
        backend:
          serviceName: basket
          servicePort: 80
      - path: /catalog-api
        backend:
          serviceName: catalog
          servicePort: 80
      - path: /identity
        backend:
          serviceName: identity
          servicePort: 80
      - path: /ordering-api
        backend:
          serviceName: ordering
          servicePort: 80
      - path: /webmvc
        backend:
          serviceName: webmvc
          servicePort: 80
      - path: /
        backend:
          serviceName: webspa
          servicePort: 80
