apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: basket
  name: basket
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: basket
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: catalog
  name: catalog
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: catalog
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: identity
  name: identity
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: identity
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: ordering
  name: ordering
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: ordering
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: webmvc
  name: webmvc
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: webmvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop
    component: webspa
  name: webspa
  namespace: shop
spec:
  ports:
  - port: 80
  selector:
    app: eshop
    component: webspa